Add website links
WarwickTabletop/tablebot pull request #101
Opened 2022-01-02 22:58 UTC by joshdavies14

Closes #73, adds `.inventory` and `.suggest boardgames` as basic commands

![image](https://user-images.githubusercontent.com/30526591/147891656-fb7293f1-6622-4ef0-b7c2-6dc627410417.png)

2022-01-03 13:10 UTC, distributive requested changes
As discussed, please create a new plugin for `suggest` and add `boardgame` as a subcommand (along with `ccg`, `wargame`, and `rpg`)

2022-01-05 21:48 UTC, finnbar approved these changes
(puts on CS141 review hat) solid, clear code! I've added two suggestions (you can just click on them to commit them) to fix some of the text the commands output, but this is just me being precise with terminology

2022-01-05 21:48 UTC, finnbar commented on src/Tablebot/Plugins/Suggest.hs
> +-- and pong.
```suggestion

```
This comment is a bit wrong, and doesn't really add anything to the documentation by being there tbh

2022-01-05 21:48 UTC, finnbar commented on src/Tablebot/Plugins/Basic.hs
> +      Simple ("the inventory", "The inventory, with a link to the actual inventory")
```suggestion
      Simple ("our board games inventory", "Our board games inventory, with a link to the actual inventory")
```
Tiny edit for clarification there - we technically have other inventories, but they're used a lot less.

2022-01-05 22:05 UTC, merged