Dice stats
WarwickTabletop/tablebot pull request #105
Opened 2022-01-04 22:43 UTC by L0neGamer

adds a subcommand to roll that performs statistics on the given expression
the statistics are turned into a graph which is uploaded to discord

currently, mathematical operators, and all forms of dice and rolling multiple dice are supported.
it is hoped that dice operations (minus keep/drop where) will be supported in future.

supporting functions is low on the list of tasks, but possible.

I invite others that wish to to contribute to this branch by performing a pull request on my branch - focussing on expanding `rangeDieOp'`, and making `rangeDieOpHelpKD` work.

2022-01-05 22:02 UTC, L0neGamer commented
https://github.com/WarwickTabletop/tablebot/issues/66 is the issue related to this branch and PR

2022-01-13 10:17 UTC, L0neGamer commented on stack.yaml
> +- git: https://github.com/L0neGamer/haskell-distribution.git
This will need updating to just `distribution-1.1.1.1` once hackage has updated, but I don't know how long that will take

2022-01-31 14:54 UTC, L0neGamer commented on stack.yaml
> +- git: https://github.com/L0neGamer/haskell-distribution.git
hackage has not updated, 20 days later. might be worth keeping it in then, or possibly pulling from the main repo? regardless, the updates within this commit are needed.

2022-02-05 17:23 UTC, finnbar requested changes
First off, this is all very cool and seems to generally hold up to testing - my comments are mainly documentation-related. I also have a few comments from my testing, which I reported to you on Discord but I'm repeating here:

* `!r 6d` reports two different errors, one with "couldn't" and another with "could not". Probably should be standardised, and maybe report one error if possible.
* Missing bracket errors (e.g. `!r maximum({d2, d2)` and `!r maximum({d2, d2}`) report the parent `WithError` rather than a more useful child error. Use `<??>` if you ever want to escape out of the `WithError`'s error. (Maybe comment on `<??>` with that?)
* `!r 2d(d6)` is incorrectly flagged as an error.

Otherwise, looks amazing!

2022-02-06 13:54 UTC, finnbar approved these changes
Approved with changes made.

2022-02-06 13:54 UTC, merged