Send replies
WarwickTabletop/tablebot pull request #58
Opened 2021-12-05 18:41 UTC by the-Bruce

Add the ability to the library to send replies. Demonstrated in reminders

2021-12-06 11:03 UTC, L0neGamer approved these changes
Tested, everything seems to work as expected

2021-12-15 11:34 UTC, finnbar requested changes
A bug arose from this, for which a solution is provided. There is also an older bug that may as well be fixed with these reminder improvements.

Also, as a quick improvement, could you provide an admin-only `.remind delete` command or similar?

2021-12-15 11:34 UTC, finnbar commented on src/Tablebot/Plugins/Reminder.hs
> +              sendCustomReplyMessage mess (Snowflake mid) False $
```suggestion
              sendCustomReplyMessage mess (Snowflake mid) True $
```
from discussion in Discord

2021-12-15 11:34 UTC, finnbar commented on src/Tablebot/Plugin/Discord.hs
> +
This all looks strong and works from brief testing (it's the reminder changes that are causing issues)

2021-12-15 11:34 UTC, finnbar commented on src/Tablebot/Plugins/Reminder.hs
>              Left _ -> pure ()
This isn't caused by your PR (it was a bug from before) - but if a reminder command's original message (the starting `.remind ...` message) is deleted, the reminder will never be reminded about and will be brought up by the database with every run of the cron job without actually doing the reminder.

2021-12-15 20:03 UTC, merged